from typing import Union, List
from urllib.parse import urlparse

import dspy

from ...interface import Retriever, Information
from ...utils import ArticleTextProcessing

# Internet source restrictions according to Wikipedia standard:
# https://en.wikipedia.org/wiki/Wikipedia:Reliable_sources/Perennial_sources
GENERALLY_UNRELIABLE = {
    "112Ukraine",
    "AdFontesMedia",
    "AlterNet",
    "Amazon",
    "AnadoluAgency(controversialtopics)",
    "Ancestry.com",
    "Answers.com",
    "Antiwar.com",
    "Anti-DefamationLeague",
    "arXiv",
    "AtlasObscuraplaces",
    "Bild",
    "BlazeMedia",
    "Blogger",
    "BroadwayWorld",
    "CaliforniaGlobe",
    "TheCanary",
    "CelebrityNetWorth",
    "CESNUR",
    "ChatGPT",
    "CNET(November2022\u2013present)",
    "CoinDesk",
    "ConsortiumNews",
    "CounterPunch",
    "CorreodelOrinoco",
    "Cracked.com",
    "DailyExpress",
    "DailyKos",
    "DailySabah",
    "TheDailyWire",
    "Discogs",
    "Distractify",
    "TheElectronicIntifada",
    "EncyclopaediaMetallum",
    "EthnicityofCelebs",
    "Facebook",
    "FamilySearch",
    "Fandom",
    "TheFederalist",
    "FindaGrave",
    "Findmypast",
    "FlagsoftheWorld",
    "Flickr",
    "Forbes.comcontributors",
    "FoxNews(politicsandscience)",
    "FoxNews(talkshows)",
    "Gawker",
    "GBNews",
    "Geni.com",
    "gnis-class",
    "gns-class",
    "GlobalSecurity.org",
    "Goodreads",
    "GuidoFawkes",
    "HeatStreet",
    "History",
    "HuffPostcontributors",
    "IMDb",
    "IndependentMediaCenter",
    "Inquisitr",
    "InternationalBusinessTimes",
    "Investopedia",
    "JewishVirtualLibrary",
    "JoshuaProject",
    "KnowYourMeme",
    "LandTransportGuru",
    "LinkedIn",
    "LiveJournal",
    "MarquisWho'sWho",
    "Mashablesponsoredcontent",
    "MEAWW",
    "MediaBias/FactCheck",
    "MediaResearchCenter",
    "Medium",
    "metal-experience",
    "Metro",
    "TheNewAmerican",
    "NewYorkPost",
    "NGOMonitor",
    "TheOnion",
    "OurCampaigns",
    "PanAmPost",
    "Patheos",
    "AnPhoblacht",
    "ThePostMillennial",
    "arXiv",
    "bioRxiv",
    "medRxiv",
    "PeerJ Preprints",
    "Preprints.org",
    "SSRN",
    "PRNewswire",
    "Quadrant",
    "Quillette",
    "Quora",
    "RawStory",
    "Reddit",
    "RedState",
    "ResearchGate",
    "RollingStone",
    "RollingStone(CultureCouncil)",
    "Scribd",
    "Scripturaltexts",
    "SimpleFlying",
    "SixthTone(politics)",
    "TheSkwawkbox",
    "SourceWatch",
    "SpiritofMetal",
    "Sportskeeda",
    "StackExchange",
    "StackOverflow",
    "MathOverflow",
    "AskUbuntu",
    "starsunfolded.com",
    "Statista",
    "TASS",
    "TheTruthAboutGuns",
    "TV.com",
    "TVTropes",
    "Twitter",
    "X.com",
    "UrbanDictionary",
    "Venezuelanalysis",
    "VGChartz",
    "VoC",
    "WashingtonFreeBeacon",
    "Weather2Travel",
    "TheWesternJournal",
    "WeGotThisCovered",
    "WhatCulture",
    "Who'sWho(UK)",
    "WhoSampled",
    "Wikidata",
    "WikiLeaks",
    "Wikinews",
    "Wikipedia",
    "WordPress.com",
    "Worldometer",
    "YouTube",
    "ZDNet",
}
DEPRECATED = {
    "AlMayadeen",
    "ANNANews",
    "BaiduBaike",
    "ChinaGlobalTelevisionNetwork",
    "TheCradle",
    "Crunchbase",
    "TheDailyCaller",
    "DailyMail",
    "DailyStar",
    "TheEpochTimes",
    "FrontPageMagazine",
    "TheGatewayPundit",
    "GlobalTimes",
    "TheGrayzone",
    "HispanTV",
    "JihadWatch",
    "Last.fm",
    "LifeSiteNews",
    "TheMailonSunday",
    "MintPressNews",
    "NationalEnquirer",
    "NewEasternOutlook",
    "NewsBreak",
    "NewsBlaze",
    "NewsoftheWorld",
    "Newsmax",
    "NNDB",
    "OccupyDemocrats",
    "OfficeofCubaBroadcasting",
    "OneAmericaNewsNetwork",
    "Peeragewebsites",
    "PressTV",
    "ProjectVeritas",
    "RateYourMusic",
    "RepublicTV",
    "RoyalCentral",
    "RT",
    "Sputnik",
    "TheSun",
    "Taki'sMagazine",
    "TasnimNewsAgency",
    "Telesur",
    "TheUnzReview",
    "VDARE",
    "VoltaireNetwork",
    "WorldNetDaily",
    "ZeroHedge",
}
BLACKLISTED = {
    "Advameg",
    "bestgore.com",
    "BreitbartNews",
    "CentreforResearchonGlobalization",
    "Examiner.com",
    "FamousBirthdays",
    "Healthline",
    "InfoWars",
    "Lenta.ru",
    "LiveLeak",
    "Lulu.com",
    "MyLife",
    "NaturalNews",
    "OpIndia",
    "ThePointsGuy",
    "ThePointsGuy(sponsoredcontent)",
    "Swarajya",
    "VeteransToday",
    "ZoomInfo",
}


def is_valid_wikipedia_source(url):
    parsed_url = urlparse(url)
    # Check if the URL is from a reliable domain
    combined_set = GENERALLY_UNRELIABLE | DEPRECATED | BLACKLISTED
    for domain in combined_set:
        if domain in parsed_url.netloc:
            return False

    return True
