[theme]
primaryColor = "#7aa2f7"
backgroundColor = "#1a1b26"
secondaryBackgroundColor = "#24283b"
textColor = "#a9b1d6"
font = "sans serif"

[server]
enableStaticServing = true

[client]
showErrorDetails = false
toolbarMode = "minimal"

[browser]
gatherUsageStats = false

[global]
developmentMode = false
